CREATE TABLE DEPLOYMENT (
	ID bigint not null GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	URL varchar(512) not null,
	FILENAME varchar(512) not null,
	DEPLOY_DATE timestamp not null,
	FAILED_RESOURCE char not null,
	RETRIES int not null,
	primary key (ID));
CREATE TABLE RESOURCE (
	ID bigint not null GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	URL varchar(512) not null,
	CRC varchar(128),
	FILENAME varchar(512) not null,
	RETRIES int not null,
	primary key (ID));
CREATE TABLE PENDING (
	DEPLOYMENT_ID bigint not null,
	RESOURCE_ID bigint not null);
ALTER TABLE PENDING ADD CONSTRAINT FK_PENDING_DEPLOYMENT FOREIGN KEY (DEPLOYMENT_ID) REFERENCES DEPLOYMENT;
ALTER TABLE PENDING ADD CONSTRAINT FK_PENDING_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE;
